#%RAML 1.0 DataType
properties: 
  PortalOrderLineNumber:
    type: string
  POLineNumber:
    type: string
  CustomerPartNumber:
    type: string
  CatalogNumber:
    type: string
  ShortPartNumber:
    type: string
  Quantity:
    type: string
  RequestDate:
    type: string