#%RAML 1.0 DataType
properties: 
  siteId: 
    type: string
  CustomerId:
    type: string
  CustomerNumber:
    type: string
  BillToLocation:
    type: string
  BillToSiteId:
    type: string
  ShipToAbbreviation:
    type: string
  ShipToSiteId:
    type: string
  PortalOrderNumber:
    type: string
  ShippingOption:
    type: string
  CustomerPONumber:
    type: string
  Notes:
    type: string
  OrderSubmitdate:
    type: string
  ActionCode:
    type: string